[Data_Params]
# use which method to preprocess original data.
# Option: 
#   - z-score(Standardlization), 
#   - min-max(Normalization), 
#   - raw (original curves)
preprocess = "z-score" 

# Use `diff_order` differencing orders. Default: 0
diff_order = 0

# Define your params used in models

# Default Settings
[Model_Params.Default]
 param_1 = 0
 param_2 = "a"

# For specific dataset, e.g. Yahoo. 
# The following config will overwrite the param_1 when training/testing Yahoo
[Model_Params.Yahoo]
 param_1 = 1