[Data_Params]
types = "UTS"
# datasets = ["AIOPS", "NAB", "WSD", "Yahoo", "UCR", "TODS"]
datasets = ["AIOPS"]
train_proportion = 1
valid_proportion = 0.2
preprocess = "raw"
diff_p = 0

[Analysis]
 plot_score = true
 plot_y_hat = true

# if your want to specify the model params for one Dataset
[Model_Params.Default]
cuda = true
p = 128
lat_dim_1 = 32
lat_dim_2 = 8
batch_size = 128
epochs = 100
lr = 0.0001
