[Data_Params]
types = "UTS"
datasets = ["AIOPS", "NAB", "WSD", "Yahoo"]
# datasets = ["NAB"]
train_proportion = 1
valid_proportion = 0
preprocess = "raw"

[Analysis]
 plot_score = true
 plot_y_hat = false

# if your want to specify the model params for one Dataset
[Model_Params.Default]