# The dataset included in statistic board 
Datasets = [
    "AIOPS", 
    "NAB", 
    "TODS", 
    "WSD", 
    "Yahoo", 
    "UCR"
]
# Datasets = [
#     "NAB", 
# ]

# The Methods included in statistic board 
Methods = [
    # prediction based
    "AR",
    "LSTMADalpha", 
    "LSTMADbeta", 

    # reconstruction based
    "AE", 
    "EncDecAD", 
    "SRCNN", 
    "AnomalyTransformer", 
    "TimesNet",

    # vae based
    "Donut", 
    "FCVAE", 

    # others
    "TFAD", 
]



[Thresholds]
 Source = ["event-based f1 under pa with mode log", "threshold"]
# The metrics you want to do statistics on in dataset level.
# By default the metrics are based on Statistic_index.Default. 
# You can specify the metric for certain datasets like UCR. Refer to **_avg.json in EvalResult directory to build your own Statistic_index. ["A", "B", ...] means do statistics on metric["A"]["B"]...
[Statistic_index]
 Default = [
    ["best f1 under pa", "f1"],
    # ["best f1 under 10-delay pa", "f1"],
    # ["best f1 under 20-delay pa", "f1"],
    # ["best f1 under 50-delay pa", "f1"],
    # ["best f1 under 150-delay pa", "f1"],
    
    ["event-based f1 under pa with mode log", "f1"],
    ["event-based f1 under 3-delay pa with mode log", "f1"],
    ["event-based f1 under 10-delay pa with mode log", "f1"],
    ["event-based f1 under 20-delay pa with mode log", "f1"],
    ["event-based f1 under 50-delay pa with mode log", "f1"],
    ["event-based f1 under 150-delay pa with mode log", "f1"],

    ["event-based f1 under pa with mode squeeze", "f1"],
    ["event-based f1 under 3-delay pa with mode squeeze", "f1"],
    ["event-based f1 under 10-delay pa with mode squeeze", "f1"],
    ["event-based f1 under 20-delay pa with mode squeeze", "f1"],
    ["event-based f1 under 50-delay pa with mode squeeze", "f1"],
    ["event-based f1 under 150-delay pa with mode squeeze", "f1"],

    # ["auroc"],
    ["auprc"],
    # ["event-based auroc under pa with mode log"],
    ["event-based auprc under pa with mode log"],
    ["3-th auprc under event-based pa with mode log"],
    ["10-th auprc under event-based pa with mode log"],
    ["20-th auprc under event-based pa with mode log"],
    ["50-th auprc under event-based pa with mode log"],
    ["150-th auprc under event-based pa with mode log"],
    # ["event-based auroc under pa with mode squeeze"],
    ["event-based auprc under pa with mode squeeze"],
    ["3-th auprc under event-based pa with mode squeeze"],
    ["10-th auprc under event-based pa with mode squeeze"],
    ["20-th auprc under event-based pa with mode squeeze"],
    ["50-th auprc under event-based pa with mode squeeze"],
    ["150-th auprc under event-based pa with mode squeeze"],
 ]
#  UCR = [
#     ["Event Detected", "detected"]
#  ]

