[Data_Params]
types = "UTS"
# datasets = ["AIOPS", "NAB", "WSD", "Yahoo"]
datasets = ["UCR", "TODS"]
train_proportion = 1
valid_proportion = 0
preprocess = "min-max"

[Analysis]
 plot_score = true
 plot_y_hat = false

[Model_Params.Default]
q = 1e-4